# Generated by Django 5.1.6 on 2025-02-23 05:55

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Category Name')),
                ('name_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Category Name')),
                ('name_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='Category Name')),
                ('is_test_page', models.BooleanField(blank=True, default=False, null=True, verbose_name='Test Page')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Publication Date')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='e_book.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': '2. Subcategory',
                'verbose_name_plural': '2. Subcategories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('e_book.category',),
        ),
        migrations.CreateModel(
            name='TopLevelCategory',
            fields=[
            ],
            options={
                'verbose_name': '1. Main Category',
                'verbose_name_plural': '1. Main Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('e_book.category',),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('time', models.CharField(blank=True, max_length=250, null=True, verbose_name='Time')),
                ('time_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Time')),
                ('time_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='Time')),
                ('duration', models.CharField(blank=True, max_length=250, null=True, verbose_name='Duration')),
                ('duration_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Duration')),
                ('duration_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='Duration')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Publication Date')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='e_book.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': '3. Contents',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Publication Date')),
                ('contentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_resource', to='e_book.content', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Content Resource',
                'verbose_name_plural': 'Content Resources',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Short Description')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Short Description')),
                ('description_uz', ckeditor.fields.RichTextField(null=True, verbose_name='Short Description')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Publication Date')),
                ('contentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_term', to='e_book.content', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Content Term',
                'verbose_name_plural': 'Content Terms',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Short Description')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Short Description')),
                ('description_uz', ckeditor.fields.RichTextField(null=True, verbose_name='Short Description')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Publication Date')),
                ('contentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_text', to='e_book.content', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Content Text',
                'verbose_name_plural': 'Content Texts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContnetExamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Short Description')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Short Description')),
                ('description_uz', ckeditor.fields.RichTextField(null=True, verbose_name='Short Description')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Publication Date')),
                ('contentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_example', to='e_book.content', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Content Example',
                'verbose_name_plural': 'Content Examples',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Quiz Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Quiz Title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Quiz Title')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='e_book.category')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': '4. Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Question Text')),
                ('text_en', models.CharField(max_length=500, null=True, verbose_name='Question Text')),
                ('text_uz', models.CharField(max_length=500, null=True, verbose_name='Question Text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='e_book.quiz')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
