# Generated by Django 5.1.6 on 2025-02-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0002_remove_question_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is Correct'),
        ),
    ]
