# Generated by Django 5.1.6 on 2025-02-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0004_remove_question_is_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Answer Text'),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Answer Text'),
        ),
    ]
