# Generated by Django 5.1.6 on 2025-02-24 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0005_answer_text_en_answer_text_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonDevelopments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson/', verbose_name='Lesson File')),
            ],
            options={
                'verbose_name': 'Lesson Development',
                'verbose_name_plural': '7. Lesson Developments',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_video', models.URLField(blank=True, null=True, verbose_name='Video URL')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': '6. Videos',
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': '5. Questions'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='e_book.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Answer Text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Answer Text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Answer Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='e_book.quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='e_book.category'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quiz Title'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quiz Title'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quiz Title'),
        ),
    ]
