# Generated by Django 5.1.6 on 2025-02-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0006_lessondevelopments_videos_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessondevelopments',
            name='name_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='lessondevelopments',
            name='name_uz',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name'),
        ),
    ]
