# Generated by Django 5.1.6 on 2025-03-06 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0008_alter_lessondevelopments_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enterpage',
            table='e_book_enterpage',
        ),
    ]
