# Generated by Django 5.1.6 on 2025-03-06 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0009_alter_enterpage_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnterPage',
            new_name='EntersPage',
        ),
        migrations.AlterModelTable(
            name='enterspage',
            table=None,
        ),
    ]
