# Generated by Django 5.1.6 on 2025-03-06 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0010_rename_enterpage_enterspage_alter_enterspage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enterspage',
            table='e_book_enterpage',
        ),
    ]
